name: Build and Release on Tag

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      arch: amd64
                      ext: ""
                    - os: macos-latest
                      arch: amd64
                      ext: ""
                    - os: macos-latest
                      arch: arm64
                      ext: ""
                    - os: windows-latest
                      arch: amd64
                      ext: ".exe"

        steps:
            - uses: actions/checkout@v4

            # Linux: apt
            - name: Install SDL2 on Linux
              if: startsWith(matrix.os, 'ubuntu')
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev pkg-config

            # macOS: brew
            - name: Install SDL2 on macOS
              if: startsWith(matrix.os, 'macos')
              run: |
                  brew install sdl2 sdl2_ttf sdl2_image pkg-config

            # Windows: MSYS2 mit pacman
            - name: Install MSYS2 and SDL2 on Windows
              if: startsWith(matrix.os, 'windows')
              uses: msys2/setup-msys2@v2
              with:
                  update: true
                  install: |
                      mingw-w64-x86_64-SDL2
                      mingw-w64-x86_64-SDL2_ttf
                      mingw-w64-x86_64-SDL2_image

            - name: Build binary
              shell: bash
              run: |
                  BIN_NAME="conways-game-of-life${{ matrix.ext }}"

                  if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
                    g++ -std=c++17 *.cpp -o "$BIN_NAME" $(pkg-config --cflags --libs sdl2 SDL2_ttf SDL2_image)
                  elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
                    # Für macOS beide Architekturen verwenden pkg-config
                    clang++ -std=c++17 *.cpp -o "$BIN_NAME" $(pkg-config --cflags --libs sdl2 SDL2_ttf SDL2_image)
                  elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
                    # Windows Build in MSYS2-Umgebung
                    g++ -std=c++17 *.cpp -o "$BIN_NAME" -lSDL2 -lSDL2_ttf -lSDL2_image
                  fi

            - name: Archive binary
              shell: bash
              run: |
                  ARCHIVE_NAME="conways-game-of-life-${{ matrix.os }}-${{ matrix.arch }}"
                  BIN_NAME="conways-game-of-life${{ matrix.ext }}"
                  if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
                    7z a "${ARCHIVE_NAME}.zip" "$BIN_NAME"
                  else
                    tar -czf "${ARCHIVE_NAME}.tar.gz" "$BIN_NAME"
                  fi

            - uses: actions/upload-artifact@v4
              with:
                  name: conways-game-of-life-${{ matrix.os }}-${{ matrix.arch }}
                  path: |
                      *.tar.gz
                      *.zip
