name: Build and Release on Tag

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      arch: amd64
                      ext: ""
                    - os: macos-latest
                      arch: amd64
                      ext: ""
                    - os: macos-latest
                      arch: arm64
                      ext: ""
                    - os: windows-latest
                      arch: amd64
                      ext: ".exe"

        steps:
            - uses: actions/checkout@v4

            # Linux: apt
            - name: Install SDL2 on Linux
              if: startsWith(matrix.os, 'ubuntu')
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev pkg-config

            # macOS: brew
            - name: Install SDL2 on macOS
              if: startsWith(matrix.os, 'macos')
              run: |
                  brew install sdl2 sdl2_ttf sdl2_image pkg-config

            # Windows: MSYS2 mit MinGW
            - name: Install MSYS2 and SDL2 on Windows
              if: startsWith(matrix.os, 'windows')
              uses: msys2/setup-msys2@v2
              with:
                  update: true
                  install: |
                      mingw-w64-x86_64-toolchain
                      mingw-w64-x86_64-SDL2
                      mingw-w64-x86_64-SDL2_ttf
                      mingw-w64-x86_64-SDL2_image
                  msystem: MINGW64

            - name: Build binary on Windows
              if: startsWith(matrix.os, 'windows')
              shell: msys2 {0}
              run: |
                  # Verwende pkg-config für die korrekten Compiler-Flags
                  g++ -std=c++17 *.cpp -o conways-game-of-life.exe \
                    $(pkg-config --cflags --libs sdl2 SDL2_ttf SDL2_image) \
                    -lSDL2main -mwindows

            - name: Copy DLLs on Windows
              if: startsWith(matrix.os, 'windows')
              shell: msys2 {0}
              run: |
                  # Kopiere SDL2-DLLs
                  cp /mingw64/bin/SDL2.dll .
                  cp /mingw64/bin/SDL2_ttf.dll .
                  cp /mingw64/bin/SDL2_image.dll .

                  # Kopiere zusätzliche DLLs für Bildformate
                  cp /mingw64/bin/libavif-16.dll .
                  cp /mingw64/bin/libjpeg-8.dll .
                  cp /mingw64/bin/libjxl.dll .
                  cp /mingw64/bin/libpng16-16.dll .

                  # Kopiere weitere möglicherweise benötigte DLLs
                  cp /mingw64/bin/libwebp-7.dll .
                  cp /mingw64/bin/libwebpdemux-2.dll .
                  cp /mingw64/bin/libwebpmux-3.dll .
                  cp /mingw64/bin/zlib1.dll .
                  cp /mingw64/bin/libwinpthread-1.dll .
                  cp /mingw64/bin/libgcc_s_seh-1.dll .
                  cp /mingw64/bin/libstdc++-6.dll .

            - name: Build binary on Unix
              if: matrix.os != 'windows-latest'
              shell: bash
              run: |
                  BIN_NAME="conways-game-of-life${{ matrix.ext }}"
                  if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
                    g++ -std=c++17 *.cpp -o "$BIN_NAME" $(pkg-config --cflags --libs sdl2 SDL2_ttf SDL2_image)
                  elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
                    clang++ -std=c++17 *.cpp -o "$BIN_NAME" $(pkg-config --cflags --libs sdl2 SDL2_ttf SDL2_image)
                  fi

            - name: Archive binary
              shell: bash
              run: |
                  ARCHIVE_NAME="conways-game-of-life-${{ matrix.os }}-${{ matrix.arch }}"
                  if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
                    # Füge alle DLLs und die sans.ttf zum ZIP-Archiv hinzu
                    7z a "${ARCHIVE_NAME}.zip" conways-game-of-life.exe *.dll sans.ttf
                  else
                    BIN_NAME="conways-game-of-life${{ matrix.ext }}"
                    # Füge sans.ttf zum TAR-Archiv hinzu
                    tar -czf "${ARCHIVE_NAME}.tar.gz" "$BIN_NAME" sans.ttf
                  fi

            - uses: actions/upload-artifact@v4
              with:
                  name: conways-game-of-life-${{ matrix.os }}-${{ matrix.arch }}
                  path: |
                      *.tar.gz
                      *.zip

    release:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  path: ./artifacts

            - name: List files in artifacts directory
              run: ls -R ./artifacts

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  files: ./artifacts/**/*
