name: Build and Release on Tag

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      arch: amd64
                      ext: ""
                    - os: macos-latest
                      arch: amd64
                      ext: ""
                    - os: macos-latest
                      arch: arm64
                      ext: ""
                    - os: windows-latest
                      arch: amd64
                      ext: ".exe"

        steps:
            - uses: actions/checkout@v4

            # Linux: apt
            - name: Install SDL2 on Linux
              if: startsWith(matrix.os, 'ubuntu')
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev

            # macOS: brew
            - name: Install SDL2 on macOS
              if: startsWith(matrix.os, 'macos')
              run: |
                  brew install sdl2 sdl2_ttf sdl2_image

            # Windows: vcpkg
            - name: Install SDL2 on Windows
              if: startsWith(matrix.os, 'windows')
              shell: bash
              run: |
                  git clone https://github.com/microsoft/vcpkg.git
                  ./vcpkg/bootstrap-vcpkg.sh
                  ./vcpkg/vcpkg install sdl2 sdl2-ttf sdl2-image:x64-windows
                  echo "VCPKG_ROOT=$PWD/vcpkg" >> $GITHUB_ENV

            - name: Build binary
              shell: bash
              run: |
                  BIN_NAME="conways-game-of-life${{ matrix.ext }}"

                  if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
                    g++ -std=c++17 *.cpp -o "$BIN_NAME" -lSDL2 -lSDL2_ttf -lSDL2_image
                  elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
                    clang++ -std=c++17 *.cpp -o "$BIN_NAME" -I/opt/homebrew/include/SDL2 -L/opt/homebrew/lib -lSDL2 -lSDL2_ttf -lSDL2_image
                  elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
                    x86_64-w64-mingw32-g++ -std=c++17 *.cpp -o "$BIN_NAME" \
                      -I"$VCPKG_ROOT/installed/x64-windows/include" \
                      -L"$VCPKG_ROOT/installed/x64-windows/lib" \
                      -lSDL2 -lSDL2_ttf -lSDL2_image
                  fi

            - name: Archive binary
              shell: bash
              run: |
                  ARCHIVE_NAME="conways-game-of-life-${{ matrix.os }}-${{ matrix.arch }}"
                  if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
                    powershell Compress-Archive -Path "$BIN_NAME" -DestinationPath "${ARCHIVE_NAME}.zip"
                  else
                    tar -czf "${ARCHIVE_NAME}.tar.gz" "$BIN_NAME"
                  fi

            - uses: actions/upload-artifact@v4
              with:
                  name: conways-game-of-life-${{ matrix.os }}-${{ matrix.arch }}
                  path: |
                      *.tar.gz
                      *.zip
